// Generated by CoffeeScript 1.4.0
(function() {
  var Body, Jungle, dirs, images, loadImages, makeGrid,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  makeGrid = function(rows, columns, fill) {
    var c, grid, r, row, _i, _j;
    grid = [];
    for (r = _i = 1; 1 <= rows ? _i <= rows : _i >= rows; r = 1 <= rows ? ++_i : --_i) {
      row = [];
      for (c = _j = 1; 1 <= columns ? _j <= columns : _j >= columns; c = 1 <= columns ? ++_j : --_j) {
        row.push(fill);
      }
      grid.push(row);
    }
    return grid;
  };

  dirs = ['up', 'down', 'left', 'right'];

  images = {};

  loadImages = function(urls) {
    var img, new_urls, todo, url, _i, _len;
    new_urls = (function() {
      var _i, _len, _results;
      _results = [];
      for (_i = 0, _len = urls.length; _i < _len; _i++) {
        url = urls[_i];
        if (!images[url]) {
          _results.push(url);
        }
      }
      return _results;
    })();
    todo = new_urls.length;
    for (_i = 0, _len = new_urls.length; _i < _len; _i++) {
      url = new_urls[_i];
      img = new Image();
      img.src = url;
      images[url] = img;
      img.onload = function() {
        return todo--;
      };
    }
    return null;
  };

  Body = (function() {

    function Body(jungle, sprite, x, y, misc) {
      var _ref, _ref1, _ref2, _ref3, _ref4;
      this.jungle = jungle;
      this.sprite = sprite;
      this.x = x;
      this.y = y;
      if (misc == null) {
        misc = {};
      }
      this.width = (_ref = misc.width) != null ? _ref : 2;
      this.height = (_ref1 = misc.height) != null ? _ref1 : 2;
      this.facing = (_ref2 = misc.facing) != null ? _ref2 : 'down';
      this.state = (_ref3 = misc.state) != null ? _ref3 : 'stopped';
      this.was_moving = (_ref4 = misc.was_moving) != null ? _ref4 : false;
    }

    Body.prototype.occupying = function() {
      var bottom_row, bottom_y, c, left_column, left_x, r, right_column, right_x, sq_height, sq_width, squares, top_row, top_y, _i, _j;
      sq_height = this.jungle.square_height;
      sq_width = this.jungle.square_width;
      top_y = this.y;
      bottom_y = top_y + this.height * sq_height;
      left_x = this.x;
      right_x = left_x + this.width * sq_width;
      top_row = Math.floor(top_y / sq_height);
      bottom_row = Math.ceil(bottom_y / sq_height) - 1;
      left_column = Math.floor(left_x / sq_width);
      right_column = Math.ceil(right_x / sq_width) - 1;
      squares = [];
      for (r = _i = top_row; top_row <= bottom_row ? _i <= bottom_row : _i >= bottom_row; r = top_row <= bottom_row ? ++_i : --_i) {
        for (c = _j = left_column; left_column <= right_column ? _j <= right_column : _j >= right_column; c = left_column <= right_column ? ++_j : --_j) {
          squares.push([r, c]);
        }
      }
      return squares;
    };

    Body.prototype.imageURLs = function() {
      var dir, i, sprite, urls, _i, _j, _k, _len, _len1, _results;
      sprite = this.sprite;
      switch (sprite) {
        case 'dartdemon':
          _results = [];
          for (_i = 0, _len = dirs.length; _i < _len; _i++) {
            dir = dirs[_i];
            _results.push("img/dartdemon/" + dir + ".png");
          }
          return _results;
          break;
        default:
          urls = [];
          for (_j = 0, _len1 = dirs.length; _j < _len1; _j++) {
            dir = dirs[_j];
            urls.push("img/" + sprite + "/stopped/" + dir + ".png");
            for (i = _k = 0; _k <= 3; i = ++_k) {
              urls.push("img/" + sprite + "/moving/" + dir + "/" + i + ".png");
            }
          }
          return urls;
      }
    };

    Body.prototype.loadImages = function() {
      return loadImages(this.imageURLs());
    };

    Body.prototype.imageURL = function() {
      var sprite;
      sprite = this.sprite;
      switch (sprite) {
        case 'dartdemon':
          return "img/dartdemon/" + this.facing + ".png";
        default:
          switch ((this.was_moving ? 'moving' : this.state)) {
            case 'stopped':
              return "img/" + sprite + "/stopped/" + this.facing + ".png";
            case 'moving':
              return "img/" + sprite + "/moving/" + this.facing + "/" + this.jungle.anim_frame + ".png";
          }
      }
    };

    Body.prototype.draw = function() {
      var j;
      j = this.jungle;
      return j.ctx.drawImage(images[this.imageURL()], this.x + j.x_offset, this.y + j.y_offset);
    };

    Body.prototype.mark = function() {
      var bodies, c, cell, r, _i, _len, _ref, _ref1, _results;
      bodies = this.jungle.bodies;
      _ref = this.occupying();
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        _ref1 = _ref[_i], r = _ref1[0], c = _ref1[1];
        cell = bodies[r][c];
        if (__indexOf.call(cell, this) < 0) {
          _results.push(cell.push(this));
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    };

    Body.prototype.unmark = function() {
      var bodies, body, c, r, _i, _len, _ref, _ref1, _results;
      bodies = this.jungle.bodies;
      _ref = this.occupying();
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        _ref1 = _ref[_i], r = _ref1[0], c = _ref1[1];
        _results.push((function() {
          var _j, _len1, _ref2, _results1;
          _ref2 = bodies[r][c](where(body !== this));
          _results1 = [];
          for (_j = 0, _len1 = _ref2.length; _j < _len1; _j++) {
            body = _ref2[_j];
            _results1.push(bodies[r][c] = body);
          }
          return _results1;
        }).call(this));
      }
      return _results;
    };

    return Body;

  })();

  Jungle = (function() {

    function Jungle(canvas, misc) {
      var c, r, _ref, _ref1, _ref2, _ref3, _ref4, _ref5;
      this.canvas = canvas;
      if (misc == null) {
        misc = {};
      }
      this.x_offset = (_ref = misc.x_offset) != null ? _ref : 0;
      this.y_offset = (_ref1 = misc.y_offset) != null ? _ref1 : 0;
      this.num_rows = r = (_ref2 = misc.num_rows) != null ? _ref2 : 24;
      this.num_columns = c = (_ref3 = misc.num_columns) != null ? _ref3 : 30;
      this.square_width = (_ref4 = misc.square_width) != null ? _ref4 : 16;
      this.square_height = (_ref5 = misc.square_height) != null ? _ref5 : 16;
      this.ctx = canvas.getContext('2d');
      this.frame = 0;
      this.anim_frame = 0;
      this.anim_subframe = 0;
      this.scenery = makeGrid(r, c, 'bare');
      this.pickups = makeGrid(r, c, null);
      this.bodies = makeGrid(r, c, []);
      this.pickup_list = [];
      this.body_list = [];
      null;
    }

    Jungle.prototype.advance = function() {
      this.frame++;
      this.anim_subframe++;
      if (this.anim_subframe === 5) {
        this.anim_subframe = 0;
        this.anim_frame = (this.anim_frame + 1) % 4;
      }
      return null;
    };

    Jungle.prototype.draw = function() {
      this.draw_scenery();
      this.draw_pickups();
      this.draw_bodies();
      return null;
    };

    Jungle.prototype.draw_scenery = function() {
      var c, r, _i, _j, _ref, _ref1;
      for (r = _i = 0, _ref = this.num_rows - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; r = 0 <= _ref ? ++_i : --_i) {
        for (c = _j = 0, _ref1 = this.num_columns - 1; 0 <= _ref1 ? _j <= _ref1 : _j >= _ref1; c = 0 <= _ref1 ? ++_j : --_j) {
          this.ctx.fillStyle = (function() {
            switch (this.scenery[r][c]) {
              case 'bare':
                return '#ffffcc';
              case 'grass':
                return '#00ff00';
              case 'water':
                return '#0033ff';
              case 'tree':
                return '#006600';
            }
          }).call(this);
          this.ctx.fillRect(c * this.square_width + this.x_offset, r * this.square_height + this.y_offset, this.square_width, this.square_height);
        }
      }
      return null;
    };

    Jungle.prototype.draw_pickups = function() {
      var pickup, _i, _len, _ref;
      _ref = this.pickup_list;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        pickup = _ref[_i];
        pickup.draw();
      }
      return null;
    };

    Jungle.prototype.draw_bodies = function() {
      var body, _i, _len, _ref;
      _ref = this.body_list;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        body = _ref[_i];
        body.draw();
      }
      return null;
    };

    Jungle.prototype.set_scenery = function(r, c, val) {
      this.scenery[r][c] = val;
      return null;
    };

    Jungle.prototype.new_body = function(r, c, sprite) {
      var body;
      body = new Body(this, sprite, c * this.square_width, r * this.square_height);
      this.body_list.push(body);
      body.mark;
      return null;
    };

    Jungle.prototype.loadImages = function() {
      var body, pickup, _i, _j, _len, _len1, _ref, _ref1;
      _ref = this.body_list;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        body = _ref[_i];
        body.loadImages();
      }
      _ref1 = this.pickup_list;
      for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
        pickup = _ref1[_j];
        pickup.loadImages();
      }
      return null;
    };

    return Jungle;

  })();

  this.Jungle = Jungle;

}).call(this);
